name: deploy-booking

on:
  push:
    branches:
      - master
    paths:
      - 'packages/booking/**'

defaults:
  run:
    working-directory: packages/booking

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      # - uses: chrislennon/action-aws-cli@v1.1
      # - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/booking/latest
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Copy files to the s3 website content bucket
        run:
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/booking/latest

      - name: Create invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/booking/latest/index.html"
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
